version: "3"

services:

  api_server:
    build: API_server/
    ports:
      - 8000:8000
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0.0-noble
    restart: always
    ports:
    - 27018:27017
    volumes:
    - /data/db
  
  proxy_server:
    build: proxy_server/
    ports:
      - 8080:8080
    depends_on:
      - mongo